name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg libopus-dev
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Verify Python version
      run: python --version
    
    - name: Verify FFmpeg installation
      run: ffmpeg -version
    
    - name: Check code syntax
      run: |
        python -m compileall .
    
    - name: Locate Opus library
      run: |
        echo "Checking for libopus..."
        find /usr -name "libopus.so*" || echo "Not found in /usr"
        
  docker-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        tags: nts-discord-bot:test
        cache-from: type=gha
        cache-to: type=gha,mode=max

